// <auto-generated />
using System;
using HotaTwitch.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotaTwitch.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HotaTwitchDbContext))]
    [Migration("20260909190237_CreateChannels")]
    partial class CreateChannels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("HotaTwitch.Infrastructure.Persistence.ChannelRecord", b =>
                {
                    b.Property<string>("ChannelId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("channel_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastStateAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_state_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("token_hash");

                    b.Property<string>("TokenHint")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("token_hint");

                    b.HasKey("ChannelId");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_channels_token_hash");

                    b.ToTable("channels", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
